version: "3.8"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSW}
      APP_DB: ${APP_DB}
      APP_USER_NAME: ${APP_DB_USER}
      APP_USER_PASSWORD: ${APP_DB_PASSW}
volumes:
  postgres-data:
  postgres-startup:
