# Generated by Django 3.1.5 on 2021-01-09 00:46

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.CharField(max_length=150, unique=True)),
                ('is_mailchimp_successful', models.BooleanField(default=False)),
                ('mailchimp_id', models.CharField(blank=True, max_length=24, null=True)),
                ('mailchimp_ip_registration', models.CharField(blank=True, max_length=24, null=True)),
                ('mailchimp_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
